import { ColorStyle, BrandColorStyle } from '../utility/styleUtility'

const brandStyle: BrandColorStyle = {
  '#f2994a': 'AColor',
  '#fccc0066': 'BColor',
  '#00000000': 'BlankColor',
}

const brandStyleSnake: BrandColorStyle = {
  '#f2994a': 'a_color',
  '#fccc0066': 'b_color',
  '#00000000': 'blank_color',
}

const brandStylePascal: BrandColorStyle = {
  '#f2994a': 'AColor',
  '#fccc0066': 'BColor',
  '#00000000': 'BlankColor',
}

const localStyle: ColorStyle[] = [
  {
    UIColor: 'UIColor(red: 0.95, green: 0.60, blue: 0.29 , alpha: 1.00)',
    color: '#f2994a',
    colorRGB: 'rgba(242, 153, 74, 1)',
    name: 'Primary / fill style 1',
    designTokenName: 'primary.fill_style_1',
    snakeCodeName: 'primary_fill_style_1',
    pascalCodeName: 'PrimaryFillStyle1',
    codeName: 'primaryFillStyle1',
    androidCodeName: 'colorPrimaryFillStyle1',
    opacity: 1,
    type: 'SOLID',
  },
  {
    UIColor: 'UIColor(red: 0.99, green: 0.80, blue: 0.00 , alpha: 0.40)',
    color: '#fccc0066',
    colorRGB: 'rgba(253, 204, 0, 0.4)',
    name: 'Primary / fill style 2',
    designTokenName: 'primary.fill_style_2',
    snakeCodeName: 'primary_fill_style_2',
    pascalCodeName: 'PrimaryFillStyle2',
    codeName: 'primaryFillStyle2',
    androidCodeName: 'colorPrimaryFillStyle2',
    opacity: 0.4,
    type: 'SOLID',
  },
  {
    UIColor: 'UIColor(red: 0.99, green: 0.80, blue: 0.90 , alpha: 1.00)',
    color: '#fccce6',
    colorRGB: 'rgba(253, 204, 230, 1)',
    name: 'Secondary / fill style 3',
    designTokenName: 'secondary.fill_style_3',
    snakeCodeName: 'secondary_fill_style_3',
    pascalCodeName: 'SecondaryFillStyle3',
    codeName: 'secondaryFillStyle3',
    androidCodeName: 'colorSecondaryFillStyle3',
    opacity: 1,
    type: 'SOLID',
  },
  {
    UIColor: 'UIColor(red: 0.0, green: 0.0, blue: 0.0 , alpha: 0.0)',
    color: '#00000000',
    colorRGB: 'rgba(0, 0, 0, 0)',
    name: 'fill Style 4',
    designTokenName: 'fill_style_4',
    snakeCodeName: 'fill_style_4',
    pascalCodeName: 'FillStyle4',
    codeName: 'fillStyle4',
    androidCodeName: 'colorFillStyle4',
    opacity: 0,
    type: 'SOLID',
  },
]

const brandingStyle: ColorStyle[] = [
  {
    type: 'SOLID',
    name: 'Branding/Light Blue',
    codeName: 'lightBlue',
    androidCodeName: 'colorLightBlue',
    pascalCodeName: 'LightBlue',
    snakeCodeName: 'light_blue',
    designTokenName: 'branding.light_Blue',
    color: '#229ebd',
    colorRGB: 'rgba(34, 158, 189, 1)',
    UIColor: 'UIColor(red: 0.13, green: 0.62, blue: 0.74 , alpha: 1.00)',
    opacity: 1,
  },
  {
    type: 'SOLID',
    name: 'Branding/Light Orange',
    codeName: 'lightOrange',
    androidCodeName: 'colorLightOrange',
    pascalCodeName: 'LightOrange',
    snakeCodeName: 'light_orange',
    designTokenName: 'branding.light_Orange',
    color: '#fd8503',
    colorRGB: 'rgba(253, 133, 3, 1)',
    UIColor: 'UIColor(red: 0.99, green: 0.52, blue: 0.01 , alpha: 1.00)',
    opacity: 1,
  },
  {
    type: 'SOLID',
    name: 'Branding/Dark Blue',
    codeName: 'darkBlue',
    androidCodeName: 'colorDarkBlue',
    pascalCodeName: 'DarkBlue',
    snakeCodeName: 'dark_blue',
    designTokenName: 'branding.dark_Blue',
    color: '#013147',
    colorRGB: 'rgba(1, 49, 71, 1)',
    UIColor: 'UIColor(red: 0.00, green: 0.19, blue: 0.28 , alpha: 1.00)',
    opacity: 1,
  },
  {
    type: 'SOLID',
    name: 'Branding/Dark Orange',
    codeName: 'darkOrange',
    androidCodeName: 'colorDarkOrange',
    pascalCodeName: 'DarkOrange',
    snakeCodeName: 'dark_orange',
    designTokenName: 'branding.dark_Orange',
    color: '#ffb70b',
    colorRGB: 'rgba(255, 183, 11, 1)',
    UIColor: 'UIColor(red: 1.00, green: 0.72, blue: 0.04 , alpha: 1.00)',
    opacity: 1,
  },
  {
    type: 'GRADIENT_LINEAR',
    name: 'Branding/Gradient Sunset',
    androidCodeName: 'colorGradientSunset',
    codeName: 'gradientSunset',
    pascalCodeName: 'GradientSunset',
    snakeCodeName: 'gradient_sunset',
    designTokenName: 'branding.gradient_Sunset',
    color: 'linear-gradient( 180deg, #ff6666 0%, #2679c6 100% )',
    colorRGB:
      'linear-gradient( 180deg, rgba(255, 102, 102, 1) 0%, rgba(38, 121, 198, 1) 100% )',
    UIColor: '',
    opacity: 1,
  },
]

const dayStyle: ColorStyle[] = [
  {
    type: 'SOLID',
    name: 'Day / Primary',
    codeName: 'primary',
    androidCodeName: 'colorPrimary',
    pascalCodeName: 'Primary',
    snakeCodeName: 'primary',
    designTokenName: 'day.primary',
    color: '#229ebd',
    colorRGB: 'rgba(34, 158, 189, 1)',
    UIColor: 'UIColor(red: 0.13, green: 0.62, blue: 0.74 , alpha: 1.00)',
    opacity: 1,
  },
  {
    type: 'SOLID',
    name: 'Day / Secondary',
    codeName: 'secondary',
    androidCodeName: 'colorSecondary',
    pascalCodeName: 'Secondary',
    snakeCodeName: 'secondary',
    designTokenName: 'day.secondary',
    color: '#fd8503',
    colorRGB: 'rgba(253, 133, 3, 1)',
    UIColor: 'UIColor(red: 0.99, green: 0.52, blue: 0.01 , alpha: 1.00)',
    opacity: 1,
  },
  {
    type: 'SOLID',
    name: 'Day/on Primary',
    codeName: 'onPrimary',
    androidCodeName: 'colorOnPrimary',
    pascalCodeName: 'OnPrimary',
    snakeCodeName: 'on_primary',
    designTokenName: 'day.on_Primary',
    color: '#ccebebeb',
    colorRGB: 'rgba(235, 235, 235, 0.8)',
    UIColor: 'UIColor(red: 0.92, green: 0.92, blue: 0.92 , alpha: 0.80)',
    opacity: 0.8,
  },
  {
    type: 'GRADIENT_LINEAR',
    name: 'Day / Accent',
    codeName: 'accent',
    androidCodeName: 'colorAccent',
    pascalCodeName: 'Accent',
    snakeCodeName: 'accent',
    designTokenName: 'day.accent',
    color: 'linear-gradient( 180deg, #ff6666 0%, #2679c6 100% )',
    colorRGB:
      'linear-gradient( 180deg, rgba(255, 102, 102, 1) 0%, rgba(38, 121, 198, 1) 100% )',
    UIColor: '',
    opacity: 1,
  },
]

const nightStyle: ColorStyle[] = [
  {
    type: 'SOLID',
    name: 'Night / Primary',
    codeName: 'primary',
    androidCodeName: 'colorPrimary',
    pascalCodeName: 'Primary',
    snakeCodeName: 'primary',
    designTokenName: 'night.primary',
    color: '#013147',
    colorRGB: 'rgba(1, 49, 71, 1)',
    UIColor: 'UIColor(red: 0.00, green: 0.19, blue: 0.28 , alpha: 1.00)',
    opacity: 1,
  },
  {
    type: 'SOLID',
    name: 'Night / Secondary',
    codeName: 'secondary',
    androidCodeName: 'colorSecondary',
    pascalCodeName: 'Secondary',
    snakeCodeName: 'secondary',
    designTokenName: 'night.secondary',
    color: '#ffb70b',
    colorRGB: 'rgba(255, 183, 11, 1)',
    UIColor: 'UIColor(red: 1.00, green: 0.72, blue: 0.04 , alpha: 1.00)',
    opacity: 1,
  },
  {
    type: 'SOLID',
    name: 'Night / on Primary',
    codeName: 'onPrimary',
    androidCodeName: 'colorOnPrimary',
    pascalCodeName: 'OnPrimary',
    snakeCodeName: 'on_primary',
    designTokenName: 'night.on_Primary',
    color: '#c8c8c8',
    colorRGB: 'rgba(200, 200, 200, 1)',
    UIColor: 'UIColor(red: 0.78, green: 0.78, blue: 0.78 , alpha: 1.00)',
    opacity: 1,
  },
  {
    type: 'GRADIENT_LINEAR',
    name: 'Night / Accent',
    codeName: 'accent',
    androidCodeName: 'colorAccent',
    pascalCodeName: 'Accent',
    snakeCodeName: 'accent',
    designTokenName: 'night.accent',
    color: 'linear-gradient( 180deg, #ff6666 0%, #2679c6 100% )',
    colorRGB:
      'linear-gradient( 180deg, rgba(255, 102, 102, 1) 0%, rgba(38, 121, 198, 1) 100% )',
    UIColor: '',
    opacity: 1,
  },
]

export {
  brandStyle,
  brandStyleSnake,
  brandStylePascal,
  localStyle,
  brandingStyle,
  dayStyle,
  nightStyle,
}
